config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :jogos
  root 'pages#home'
  get '/home' => 'pages#home'
  get '/sobre' => 'pages#sobre'
  get '/contato' => 'pages#contato'
  get '/meus_jogos' => 'jogos#meus_jogos'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.admin?
      can :manage, :all
    else
      can :update, Jogo do |jogo|
        jogo.user == user
      end
      can :destroy, Jogo do |jogo|
        jogo.user == user
      end
      can :create, Jogo
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/jogo.rb
class Jogo < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :jogos
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

rescue_from CanCan::AccessDenied do |exception|
  redirect_to '/jogos', :alert => exception.message
end
end

app/controllers/jogos_controller.rb
class JogosController < ApplicationController
  before_action :set_jogo, only: [:show, :edit, :update, :destroy]

  # GET /jogos
  # GET /jogos.json
  def index
    @jogos = Jogo.all
  end
  def meus_jogos
    @jogos = Jogo.all
  end

  # GET /jogos/1
  # GET /jogos/1.json
  def show
  end

  # GET /jogos/new
  def new
    @jogo = Jogo.new
  end

  # GET /jogos/1/edit
  def edit
    authorize! :update, @jogo
  end

  # POST /jogos
  # POST /jogos.json
  def create
    @jogo = Jogo.new(jogo_params)
    @jogo.user = current_user
    respond_to do |format|
      if @jogo.save
        format.html { redirect_to @jogo, notice: 'O jogo foi publicado com sucesso' }
        format.json { render :show, status: :created, location: @jogo }
      else
        format.html { render :new }
        format.json { render json: @jogo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jogos/1
  # PATCH/PUT /jogos/1.json
  def update
    authorize! :update, @jogo
    respond_to do |format|
      if @jogo.update(jogo_params)
        format.html { redirect_to @jogo, notice: 'O jogo foi atualizado com sucesso' }
        format.json { render :show, status: :ok, location: @jogo }
      else
        format.html { render :edit }
        format.json { render json: @jogo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jogos/1
  # DELETE /jogos/1.json
  def destroy
    authorize! :destroy, @jogo
    @jogo.destroy
    respond_to do |format|
      format.html { redirect_to jogos_url, notice: 'A publicação foi apagada com sucesso' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_jogo
      @jogo = Jogo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def jogo_params
      params.require(:jogo).permit(:Nome, :Description, :user_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def contato
  end
  def sobre
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jogos_helper.rb
module JogosHelper
end

app/views/jogos/_form.html.erb
<%= form_for(@jogo) do |f| %>
  <% if @jogo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@jogo.errors.count, "error") %> prohibited this jogo from being saved:</h2>

      <ul>
      <% @jogo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <h3><%= f.label :Título %><br></h3>
    <%= f.text_area :Nome %>
  </div>
  <div class="field">
    <h3><%= f.label :Descrição %><br></h3>
    <%= f.text_area :Description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jogos/edit.html.erb
<h1>Editing Jogo</h1>

<%= render 'form' %>

<button type="button">
<%= link_to 'Mostrar', @jogo %>
</button>
<button type="button">
<%= link_to 'Voltar', url_for(:back) %>
</button>

app/views/jogos/index.html.erb
<h1>Lista de Jogos</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <button type="button">
      <%= link_to 'Novo Jogo', new_jogo_path %>
    </button>
    <div>
    <% @jogos.each do |jogo| %>
      <tr>
        <p>
          <h3><strong><%= jogo.Nome %></strong></h3>
        </p>

        <p>

          <g class="content"><%= jogo.Description %></g>
        </p>

        <g><p class="time"><%= jogo.created_at %></p></g>
          <p>
          <button type="button">
          <strong><%= link_to 'Mostrar', jogo %></strong>
        </button>
        <% if can? :update, jogo %>
        <button type="button">
        <strong><%= link_to 'Editar', edit_jogo_path(jogo) %></strong>
      </button>
        <% end %>
        <% if can? :destroy, jogo %>
        <button type="button">
        <strong><%= link_to 'Deletar', jogo, method: :delete, data: { confirm: 'Tem certeza?' } %></strong>
      </button>
        <% end %>
      </p>
      </tr>
    <% end %>
  </tbody>
</div>
</table>

<br>

app/views/jogos/meus_jogos.html.erb
<h1>Meus Jogos</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <div>
    <% @jogos.each do |jogo| %>
      <tr>
        <% if can? :destroy, jogo %>
        <p>
          <h3><strong><%= jogo.Nome %></strong></h3>
        </p>

        <p>

          <g class="content"><%= jogo.Description %></g>
        </p>

        <g><p class="time"><%= jogo.created_at %></p></g>
          <p>
          <button type="button">
          <strong><%= link_to 'Mostrar', jogo %></strong>
        </button>
        <% if can? :update, jogo %>
        <button type="button">
        <strong><%= link_to 'Editar', edit_jogo_path(jogo) %></strong>
      </button>
        <% end %>
        <% if can? :destroy, jogo %>
        <button type="button">
        <strong><%= link_to 'Deletar', jogo, method: :delete, data: { confirm: 'Tem certeza?' } %></strong>
      </button>
        <% end %>
      </p>
      <% end %>
      </tr>
    <% end %>
  </tbody>
</div>
</table>

<br>

app/views/jogos/new.html.erb
<h1>New Jogo</h1>

<%= render 'form' %>

<button type="button">
<%= link_to 'Voltar', jogos_path %>
</button>

app/views/jogos/show.html.erb
<p>
  <h3><strong>Título:</strong>
  <%= @jogo.Nome %></h3>
</p>

<p>
  <h3><strong>Descrição:</strong></h3>
  <%= @jogo.Description %>
</p>
<% if can? :update, @jogo %>
<button type="button">
<%= link_to 'Editar', edit_jogo_path(@jogo) %>
</button>
<% end %>
<button type="button">
<%= link_to 'Voltar', jogos_path %>
</button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Projeto2" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>
    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Game Suggestions</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Home", "/home"  %></li>

            <% if user_signed_in? %>
              <li><%= link_to "Lista de Jogos", "/jogos"  %></li>
              <li><%= link_to "Meus Jogos", "/meus_jogos" %></li>
              <li><%= link_to "Configurações", edit_user_registration_path %></li>
              <li><%= link_to "Sair", destroy_user_session_path, method: :delete  %></li>
            <% else %>
            <li><%= link_to "Cadastrar", new_user_registration_path  %></li>
            <li><%= link_to "Logar", new_user_session_path  %></li>
             <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li><%= link_to "Sobre", "/sobre"  %></li>
              <li><%= link_to "Contato", "/contato"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/pages/contato.html.erb
<h1>Contato</h1>
<p>
  Caso relate algum erro, mau funcionamento ou
</p>
<p>
  queira dar sugestões de melhora para o site,
</p>
<p>
   entre em contato conosco pelo e-mail
</p>
<p>
  weyler180@hotmail.com e nos
</p>
<p>
  dê sua opinião.
</p>

app/views/pages/home.html.erb
<div class="main">
  <div class="container">
    <h2>Game Suggestions</h2>
    <p>Compartilhe o seu jogo</p>
  </div>
</div>

app/views/pages/sobre.html.erb
<h1>Sobre</h1>
<p>
  Este é um trabalho criado pelo aluno Weyler Almeida
</p>
<p>
  para a disciplina de Orientação a objetos, ministrada
</p>
<p>
  pelo professor Renato Coral Sampaio
</p>
<p>
  na Universidade de Brasília.
</p>
<p>
</p>
<p>
  O serviço prestado pelo site
</p>
<p>
  é de sugestão de jogos entre
</p>
<p>
  os usuários.
</p>
<p>
  Sinta-se livre para compartilhar
</p>
<p>
  o seu jogo.
</p>